### ISSUE TITLE
The site title and logo should link to "home"

### ISSUE THREAD

**Issue by sharpchi** [hugoacfs/thefeed#58]
![image](https://user-images.githubusercontent.com/3774280/77746544-f88f0200-7014-11ea-978b-648801d74a78.png)
Though it probably depends what you think of as home.
Logged in: Home = Timeline
Not Logged in: Home = Home

**Comment by hugoacfs** [comment]
I've thought about this before, if I change it, I need to implement a way of scrolling back up easily - I think I know how - thanks to bootstrap it should be a piece of cake, I'll give it a try

**Comment by hugoacfs** [comment]
see latest commit 'addressing issue #58' for fix

**Comment by hugoacfs** [comment]
I think this is fixed in latest version
